---
- name: gitlab_runner_systemd_reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: gitlab_runner_restart
  ansible.builtin.service:
    name: "gitlab-runner-{{ item.name }}"
    state: restarted
    enabled: true
  loop: "{{ gitlab_runner_docker_instances }}"
  when: item.state == "present"
